# Indexing  of array (numpy)

In [2]:
import numpy as np

In [5]:
a1 = np.arange(1,11,2)
print(a1)
print(a1[2:])
print(a1[5:2:-1])

[1 3 5 7 9]
[5 7 9]
[9 7]


In [12]:
r = np.random.random((2,2))
print(type(r))

<class 'numpy.ndarray'>


In [16]:
r = (np.random.random((2,2))*100).astype(int)
print(r)

[[93 20]
 [91 28]]


In [22]:
r = (np.random.rand(4,4)*100).astype(int)
print(r)

[[ 7 89 59  1]
 [21 82 12 85]
 [16 90  9 13]
 [61 16 49 74]]


In [76]:
r = (np.random.rand(4,4)*100).astype(int)
print(r)
print("=="*50)
# print("[1:3,0:2]  :",r[1:3,0:2])
# print(r[-3:-1,-1])
print(r[:,::2])

[[63 62  4 12]
 [25 62 35 54]
 [37 32 76 67]
 [76 74  0 88]]
[[63  4]
 [25 35]
 [37 76]
 [76  0]]


In [78]:
# slicing on matrix
# r = (np.random.rand(4,4,4)*100).astype(int)
print(r)
print("=="*50)
# print(r[-3:-2,-2:,-4:])
print(r[:,::2])

[[[ 3  6  9 17]
  [59  4 98 56]
  [83 15 74 54]
  [10 95 31 24]]

 [[99 58 65 53]
  [65 87 45 98]
  [43 35 16 64]
  [31 46 63 70]]

 [[63 23 34 40]
  [75 38 89  0]
  [27  4 55 68]
  [ 5  7  8 37]]

 [[73 23 54 10]
  [66 52 67 62]
  [13 79 93 39]
  [24 19  0 49]]]
[[[ 3  6  9 17]
  [83 15 74 54]]

 [[99 58 65 53]
  [43 35 16 64]]

 [[63 23 34 40]
  [27  4 55 68]]

 [[73 23 54 10]
  [13 79 93 39]]]


In [100]:
# slicing on a tensor (more than 2 X 2 )
# a = (np.random.random((2,2,6))*100).astype(int)
print(a)
print("\n","===="*20,"\n")
# print(a[-1:-2:-1,-1,2])
print(a[0,0])


[[[45 59 23 42 36 41]
  [ 3 60 42 63  1 70]]

 [[87 60 69 97 83 60]
  [38 69 22 84 98 71]]]


[45 59 23 42 36 41]


# Aggergate Function
- sum()
- mean()
- median()
- min() , max()
- std()
- var()

In [3]:
# a = (np.random.random(10)*10).astype(int)
a=np.array([10,20,30,40,50,60,80])
# print("Sum :" , sum(a))
print(a)
print("Standardiation :" , a.std())
print("Mean :" , a.mean())
print("variation :" , a.var())

[10 20 30 40 50 60 80]
Standardiation : 22.31499907401901
Mean : 41.42857142857143
variation : 497.95918367346934
